export enum FeatureName {
  MAINTENANCE = 'maintenance',
  LAUNCH_POPUP = 'launch-popup',
  RANKINGS = 'rankings_variant',
  EMOTE_CATEGORIES = 'emote-categories',
  CAMPAIGN_HOMEPAGE_BANNER = 'campaign-homepage-banner',
  CAMPAIGN_COLLECTIBLES_BANNER = 'campaign-collectibles-banner',
  CAMPAIGN_BROWSER = 'campaign-browser',
  PRICE_FILTER = 'price-filter',
  ESTATE_SIZE_FILTER = 'estate-size-filter',
  LOCATION_FILTER = 'location-filter',
  CREATOR_FILTER = 'creator-filter',
  RENTAL_PERIOD_FILTER = 'rental-period-filter',
  MAP_VIEW_FILTERS = 'map-view-filters',
  RENTAL_PRICE_FILTER_CHART = 'rental-price-fitler-chart',
  HANDS_CATEGORY = 'hands-category',
  EMOTES_V2 = 'emotes-2.0',
  EMOTES_V2_FTU = 'emotes-2.0-ftu',
  NEW_NAVBAR_DROPDOWN = 'new-navbar-dropdown',
  SMART_WEARABLES_FTU = 'smart-wearables-ftu',
  MARKETPLACE_SERVER = 'marketplace-server'
}
