export const MANA_ADDRESS = process.env.REACT_APP_MANA_ADDRESS!
export const MARKETPLACE_ADDRESS = process.env.REACT_APP_MARKETPLACE_ADDRESS!
export const ESTATE_REGISTRY_ADDRESS = process.env.REACT_APP_ESTATE_ADDRESS!
