name: CI

on: [push, pull_request]

jobs:
  Build-and-test-webapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test -- --coverage
        if: ${{ always() }}
    finish:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Coveralls Finished
          uses: coverallsapp/github-action@master
          with:
            github-token: ${{ secrets.github_token }}
            parallel-finished: true
  Build-and-test-indexer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./indexer
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install
        run: npm ci
      - name: Build
        run: |
          npm run build-data -- --network mainnet
          npm run codegen
          npm run build
