name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # @v4.3.0
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: webapp/package-lock.json
      - name: Install
        run: npm install
      - name: Test
        run: npm run test:coverage
      - name: report coverage
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # @main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: ./webapp
          path-to-lcov: ./webapp/coverage/lcov.info
          fail-on-error: false
